Adding app insight test

diff --git a/terragrunt-multi-envs/templates/job-terragruntplan-template.yaml b/terragrunt-multi-envs/templates/job-terragruntplan-template.yaml
--- a/terragrunt-multi-envs/templates/job-terragruntplan-template.yaml
+++ b/terragrunt-multi-envs/templates/job-terragruntplan-template.yaml
@@ -38,11 +38,17 @@ jobs:
             export ARM_USE_OIDC=true
             export PIPELINE_TOKEN=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv)
 
+            instrumentation_key=$(az keyvault secret show --id https://g3scckv-cpms-mma-f07c-kv.vault.azure.net/secrets/instkey/a68523ce6abf4d77addf4cfbc247fbd1 --query value -o tsv)
+            api_key=$(az keyvault secret show --id https://g3scckv-cpms-mma-f07c-kv.vault.azure.net/secrets/G3Sc-CPMS-MMahdavian-app-insights-appi-api-key/59750d02a3bc498abcf7e30d4d01e936 --query value -o tsv)
+
             echo "##vso[task.setvariable variable=ARMClient;issecret=true]$ARM_CLIENT_ID"
             echo "##vso[task.setvariable variable=OIDCToken;issecret=true]$ARM_OIDC_TOKEN"
             echo "##vso[task.setvariable variable=SubID;issecret=true]$ARM_SUBSCRIPTION_ID"
             echo "##vso[task.setvariable variable=TenantID;issecret=true]$ARM_TENANT_ID"
             echo "##vso[task.setvariable variable=pipelineToken;issecret=true]$PIPELINE_TOKEN"
+            echo "##vso[task.setvariable variable=instrumentationKey;issecret=true]$instrumentation_key"
+            echo "##vso[task.setvariable variable=apiKey;issecret=true]$api_key"
+
 
             git pull https://Azure163ent-CloudOperations:$PIPELINE_TOKEN@dev.azure.com/Azure163ent-CloudOperations/ESLZ-light_template/_git/L1_blueprint_base?ref=20241015.1
             cd $(Build.SourcesDirectory)/landing_zones_*/${{ parameters.eslzEnvFolder}}/${{ layer }}/
@@ -99,6 +105,97 @@ jobs:
           ARM_USE_OIDC: true
           PIPELINE_TOKEN: $(pipelineToken)
 
+       - task: bash@3
+        name: AppInsightsLogs
+        inputs:
+          targetType: inline
+          # arguments: '$(APP_INSIGHTS_INSTRUMENTATION_KEY) $(APP_INSIGHTS_API_KEY) "Terragrunt Init" "$(Build.DefinitionName)" "$(Build.BuildNumber)"'
+          script: |
+            #!/bin/bash
+
+            function display_changes() {
+              local action=$1
+              jq --arg action "$action" -r '.resource_changes[] | select(.change.actions | contains([$action])) | .address' plan.json | while IFS= read -r line; do printf "%s\n" "$line"; done
+            }
+
+            # Define input parameters
+            appId="$INSTRUMENTATION_KEY"
+            apiKey="$API_KEY"
+            eventName="Terragrunt Plan $(System.TeamProject) ${{ layer }}"
+            pipelineName="$(Build.DefinitionName)"
+            buildNumber="$(Build.BuildNumber)"
+            org="$(System.CollectionUri)"
+            project="$(System.TeamProject)"
+            fullURL="$org$project"
+            run="$fullURL/_build/results?buildId=$(Build.BuildId)"
+            subscription_id=$(grep -Po '^\s*subscription_id\s*=\s*"\K[^"]+' $(Build.SourcesDirectory)/landing_zones_*/${{ parameters.eslzEnvFolder}}/config.hcl)
+
+
+            cd $(Build.SourcesDirectory)/landing_zones_*/${{ parameters.eslzEnvFolder}}/${{ layer }}/
+            terragrunt show -json $(Build.ArtifactStagingDirectory)/plan.tfplan > plan.json
+            
+            create=$(display_changes "create")
+            update=$(display_changes "update")
+            delete=$(display_changes "delete")
+
+            tfOutput=$(printf "Resources that will be created:\n%s\n\nResources that will be updated:\n%s\n\nResources that will be deleted:\n%s\n" "$create" "$update" "$delete")
+            
+
+            # Set headers for the HTTP request
+            headers=(
+                -H "Content-Type: application/json"
+                -H "X-Api-Key: $apiKey"
+            )
+
+            # Escape the newlines for JSON
+            escaped_tfOutput=$(echo "$tfOutput" | jq -aRs .)
+
+            # Set the body of the HTTP request
+            body=$(jq -n \
+              --arg appId "$appId" \
+              --arg eventName "$eventName" \
+              --arg pipelineName "$pipelineName" \
+              --arg buildNumber "$buildNumber" \
+              --arg subID "$subscription_id" \
+              --arg project "$fullURL" \
+              --arg runID "$run" \
+              --arg tfOutput "$escaped_tfOutput" \
+              --arg time "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
+              '{
+                name: "Microsoft.ApplicationInsights.Event",
+                time: $time,
+                iKey: $appId,
+                data: {
+                  baseType: "EventData",
+                  baseData: {
+                    name: $eventName,
+                    properties: {
+                      PipelineName: $pipelineName,
+                      BuildNumber: $buildNumber,
+                      subID: $subID,
+                      project: $project,
+                      runID: $runID,
+                      TFOutput: $tfOutput | fromjson
+                    }
+                  }
+                }
+              }')
+
+            # Define the URI for the telemetry event
+            uri="https://dc.services.visualstudio.com/v2/track"
+
+            # Make the HTTP POST request
+            response=$(curl -s -X POST "${headers[@]}" -d "$body" "$uri")
+
+            # Check if the response was successful
+            if [ $? -eq 0 ]; then
+              echo "Response: $response"
+            else
+              echo "Failed to send telemetry"
+            fi
+        env:
+          INSTRUMENTATION_KEY: $(instrumentationKey)
+          API_KEY: $(apiKey)
 
       - task: bash@3
         name: CommentPlanOnPR
